Repository LibreELEC/actions, pull requests merged in 2022-10, with the labels that each got.

#22 Add R40 to LE10
  .github/workflows/nightly-LE10.yml
Labels: LE 10.0

#23 build-images.yml: fix R40
  .github/workflows/nightly-LE10.yml
Labels: LE 10.0

#21 copy img.gz.sha256 files as well as the img.gz files for OFFICIAL releases
  .github/workflows/make-image.yml
Labels: LE 10.0, Scripts

#24 Add GitHub workflow for updating cacert.pem certificate bundle
  .github/workflows/update-cacert-pem-certificate-bundle.yml
Labels: LE 11.0, Scripts

#25 make-images.yml: fix tar upload at official images
  .github/workflows/make-image.yml
Labels: LE 10.0, LE 11.0, Images

#26 cacert-pem: use refs/heads/master as the ref
  .github/workflows/update-cacert-pem-certificate-bundle.yml
Labels: LE 11.0, Scripts

#27 Fix Job name
  .github/workflows/tools-update-addon-repo.yml
Labels: Scripts
