Repository LibreELEC/actions, pull requests merged in 2022-07, with the labels that each got.

#8 upload to device folder $version/$project/$device
  .github/workflows/make-image.yml
Labels: LE 10.0, LE 11.0, Images

#10 clean-img: fix find syntax
  .github/workflows/clean-img.yml
Labels: LE 11.0, Scripts

#11 make-image: add missing quotes in upload test
  .github/workflows/make-image.yml
Labels: LE 11.0, Scripts

#15 make-image: set the DEVICE to Generic
  .github/workflows/make-image.yml
Labels: LE 10.0, Scripts, Cleanup

#16 docs: enable proper auto update
  docs/build-lxc-gha-runner.md
Labels: Docs
