Repository LibreELEC/actions, pull requests merged in 2022-06, with the labels that each got.

#2 Remove build targets that are not available for LibreELEC 10.0
  .github/workflows/clean-hotdog-full.yml
  .github/workflows/nightly-LE10.yml
Labels: LE 10.0, Cleanup

#3 only keep two copies of images and remove any 0 size files
  .github/workflows/clean-img.yml
Labels: Cleanup

#4 add Generic-legacy project
  .github/workflows/build-images.yml
Labels: LE 11.0, Images

#5 set timeout-minutes to 8 hours as jobs are not completing
  .github/workflows/create-addon.yml
Labels: LE 11.0, Scripts, Add-ons

#6 copy img.gz.sha256 files as well as the img.gz and clean up the sha256 files
  .github/workflows/clean-img.yml
  .github/workflows/make-image.yml
Labels: Scripts

#7 force removal of the files
  .github/workflows/clean-img.yml
Labels: Scripts, Cleanup
